name: Run Python Script

on:
  push:
  
env:
  api_key: dumb

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      - name: install openai
        run: pip install openai
        
      - name: run main
        run: python main.py
