name: Run Python Script

on:
  push:
  
env:
  api_key: dumb

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run Python Script
        run:
          pip install openai
          python main.py
